### ISSUE TITLE
petsc4py

### ISSUE THREAD

**Issue by moghimis** [JesseLu/petsc4py-tutorial#1]
Dear Jesse,
I enjoyed your petsc4py examples. Did you find time to work on this more. Do you have any examples for how to connect numpy arrays to mpi matrices back and forth?
Would you mind to share more scripts?

regards,
Saeed.

**Comment by JesseLu** [comment]
Hi Saeed,

Sorry it took me so long to respond. Unfortunately I moved on from petsc4py and the progress in the repository is all I was able to achieve.
